# -*- coding: utf-8 -*-
"""correct code of KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YTrdQL6f7482ntJD9jPGqszWtIc_w9pT
"""

# 📚 Imports
import pandas as pd
import numpy as np
import joblib
import gradio as gr
import matplotlib.pyplot as plt
import io
from PIL import Image
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from imblearn.over_sampling import SMOTE
from sklearn.metrics import accuracy_score, precision_score, recall_score

# 📥 Load Dataset
df = pd.read_csv("/content/healthcare-dataset-stroke-data.csv")
df = df.dropna()

# 🔠 Encode Categorical Features
gender_le = LabelEncoder()
ever_married_le = LabelEncoder()
work_type_le = LabelEncoder()
residence_le = LabelEncoder()
smoking_le = LabelEncoder()

df['gender'] = gender_le.fit_transform(df['gender'])
df['ever_married'] = ever_married_le.fit_transform(df['ever_married'])
df['work_type'] = work_type_le.fit_transform(df['work_type'])
df['Residence_type'] = residence_le.fit_transform(df['Residence_type'])
df['smoking_status'] = smoking_le.fit_transform(df['smoking_status'])

joblib.dump(gender_le, 'gender_encoder.pkl')
joblib.dump(ever_married_le, 'ever_married_encoder.pkl')
joblib.dump(work_type_le, 'work_type_encoder.pkl')
joblib.dump(residence_le, 'residence_encoder.pkl')
joblib.dump(smoking_le, 'smoking_encoder.pkl')

# 🧠 Features & Target
X = df.drop(['id', 'stroke'], axis=1)
y = df['stroke']

# ⚖️ Data Balancing
smote = SMOTE()
X_resampled, y_resampled = smote.fit_resample(X, y)

# 🚂 Train Model
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_resampled, y_resampled)
joblib.dump(model, 'model.pkl')

# ✅ Model Evaluation
y_pred = model.predict(X_resampled)
print(f"Accuracy: {accuracy_score(y_resampled, y_pred):.2f}")
print(f"Precision: {precision_score(y_resampled, y_pred):.2f}")
print(f"Recall: {recall_score(y_resampled, y_pred):.2f}")

# 🎯 Severity Grading
def severity_level(prob):
    if prob > 0.6:
        return "🔴 High Risk"
    elif prob > 0.3:
        return "🟠 Medium Risk"
    else:
        return "🟢 Low Risk"

# 🧮 Prediction Function with Dashboard
def predict_stroke(age, hypertension, heart_disease, avg_glucose_level, bmi,
                   gender, ever_married, work_type, residence_type, smoking_status):
    try:
        # Load encoders & model
        model = joblib.load('model.pkl')
        gender_le = joblib.load('gender_encoder.pkl')
        ever_married_le = joblib.load('ever_married_encoder.pkl')
        work_type_le = joblib.load('work_type_encoder.pkl')
        residence_le = joblib.load('residence_encoder.pkl')
        smoking_le = joblib.load('smoking_encoder.pkl')

        # Prepare input
        input_dict = {
            'gender': gender_le.transform([gender])[0],
            'age': float(age),
            'hypertension': int(hypertension),
            'heart_disease': int(heart_disease),
            'ever_married': ever_married_le.transform([ever_married])[0],
            'work_type': work_type_le.transform([work_type])[0],
            'Residence_type': residence_le.transform([residence_type])[0],
            'avg_glucose_level': float(avg_glucose_level),
            'bmi': float(bmi),
            'smoking_status': smoking_le.transform([smoking_status])[0]
        }

        column_order = ['gender', 'age', 'hypertension', 'heart_disease',
                        'ever_married', 'work_type', 'Residence_type',
                        'avg_glucose_level', 'bmi', 'smoking_status']
        input_df = pd.DataFrame([input_dict])[column_order]

        # Predict
        prediction = model.predict(input_df)[0]
        probability = model.predict_proba(input_df)[0][1]
        result = "✅ No Stroke" if prediction == 0 else "⚠️ Stroke Likely"
        severity = severity_level(probability)

        # 📊 Risk Dashboard
        risk_categories = ['Low Risk', 'Medium Risk', 'High Risk']
        risk_values = [0, 0, 0]
        if probability <= 0.3:
            risk_values[0] = probability
        elif probability <= 0.6:
            risk_values[1] = probability
        else:
            risk_values[2] = probability

        fig, ax = plt.subplots()
        bars = ax.bar(risk_categories, risk_values, color=['green', 'orange', 'red'])
        ax.set_ylim(0, 1)
        ax.set_title("Stroke Risk Probability Dashboard")
        ax.set_ylabel("Probability")

        for i, bar in enumerate(bars):
            yval = bar.get_height()
            if yval > 0:
                plt.text(bar.get_x() + bar.get_width()/2, yval + 0.05, round(yval, 2),
                         ha='center', va='bottom', fontsize=12, fontweight='bold')

        plt.tight_layout()
        buf = io.BytesIO()
        plt.savefig(buf, format='png')
        buf.seek(0)
        dashboard_img = Image.open(buf)
        plt.close(fig)

        return (
            f"Prediction: {result}\n"
            f"Probability of Stroke: {probability:.2f}\n"
            f"Severity Level: {severity}\n"
            f"(Note: This is based on trained model patterns. Consult medical professionals for real diagnosis.)",
            dashboard_img
        )

    except Exception as e:
        return f"❌ Error: {e}", None

# 🎛️ Gradio Interface
# demo = gr.Interface(
#     fn=predict_stroke,
#     inputs=[
#         gr.Number(label="Age"),
#         gr.Radio([0, 1], label="Hypertension (0 = No, 1 = Yes)"),
#         gr.Radio([0, 1], label="Heart Disease (0 = No, 1 = Yes)"),
#         gr.Number(label="Average Glucose Level"),
#         gr.Number(label="BMI"),
#         gr.Radio(['Male', 'Female', 'Other'], label="Gender"),
#         gr.Radio(['Yes', 'No'], label="Ever Married"),
#         gr.Radio(['Private', 'Self-employed', 'Govt_job', 'children', 'Never_worked'], label="Work Type"),
#         gr.Radio(['Urban', 'Rural'], label="Residence Type"),
#         gr.Radio(['formerly smoked', 'never smoked', 'smokes', 'Unknown'], label="Smoking Status")
#     ],
# )
# 🎛️ Improved Gradio Interface (Better Layout)
with gr.Blocks(theme="default") as demo:
    gr.Markdown("## 🧠 Stroke Risk Predictor (KNN with Dashboard)")
    gr.Markdown("Enter patient symptoms and health details to predict stroke risk and visualize probability.")

    with gr.Row():
        with gr.Column(scale=1):
            age = gr.Number(label="Age")
            hypertension = gr.Radio([0, 1], label="Hypertension (0 = No, 1 = Yes)")
            heart_disease = gr.Radio([0, 1], label="Heart Disease (0 = No, 1 = Yes)")
            avg_glucose = gr.Number(label="Average Glucose Level")
            bmi = gr.Number(label="BMI")
            gender = gr.Radio(['Male', 'Female', 'Other'], label="Gender")
            ever_married = gr.Radio(['Yes', 'No'], label="Ever Married")
            work_type = gr.Radio(['Private', 'Self-employed', 'Govt_job', 'children', 'Never_worked'], label="Work Type")
            residence = gr.Radio(['Urban', 'Rural'], label="Residence Type")
            smoking = gr.Radio(['formerly smoked', 'never smoked', 'smokes', 'Unknown'], label="Smoking Status")
            submit_btn = gr.Button("🔍 Submit")
            clear_btn = gr.ClearButton([age, hypertension, heart_disease, avg_glucose, bmi, gender,
                                        ever_married, work_type, residence, smoking])

        with gr.Column(scale=2):
            result_box = gr.HTML(label="Prediction Result")
            graph_box = gr.Image(type="pil", label="Stroke Risk Probability Dashboard")

    submit_btn.click(
        predict_stroke,
        inputs=[age, hypertension, heart_disease, avg_glucose, bmi, gender,
                ever_married, work_type, residence, smoking],
        outputs=[result_box, graph_box]
    )

    # Removed redundant title and description from gr.Blocks definition
    # title="🧠 Stroke Risk Predictor (KNN with Dashboard)",
    # description="Enter patient symptoms and health details to predict stroke risk and visualize probability."


# 🚀 Launch
demo.launch()